name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  # google_maps_flutter: ^0.4.0
  google_maps_flutter: 
    git:
      url: git://github.com/awazgyawali/plugins/
      path: packages/google_maps_flutter
      ref: google_maps_polyline

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/bike.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf