name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_launcher_icons: "^0.7.0"
  google_maps_flutter: 
    git:
      url: git://github.com/awazgyawali/plugins/
      path: packages/google_maps_flutter
      ref: google_maps_polyline

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/bike.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/bike.png
    - assets/bikeMarker.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf